// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGSjOkXCgVbl4uZZWqXKkFTcbZVXHMFEc',
    appId: '1:74866461770:web:218c38c491263fb53f6ab3',
    messagingSenderId: '74866461770',
    projectId: 'm-espresso',
    authDomain: 'm-espresso.firebaseapp.com',
    storageBucket: 'm-espresso.firebasestorage.app',
    measurementId: 'G-8ZZMZE1DP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxMTlVQVl9rZAaXTHDfeyA2ubOCNwwJWo',
    appId: '1:74866461770:android:9fcc372351207b303f6ab3',
    messagingSenderId: '74866461770',
    projectId: 'm-espresso',
    storageBucket: 'm-espresso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9AX_0GlNNdJ5FNsszI8oAHzbiXlOAu30',
    appId: '1:74866461770:ios:dadb259f65c162db3f6ab3',
    messagingSenderId: '74866461770',
    projectId: 'm-espresso',
    storageBucket: 'm-espresso.firebasestorage.app',
    iosBundleId: 'com.example.flutterCoffeeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9AX_0GlNNdJ5FNsszI8oAHzbiXlOAu30',
    appId: '1:74866461770:ios:dadb259f65c162db3f6ab3',
    messagingSenderId: '74866461770',
    projectId: 'm-espresso',
    storageBucket: 'm-espresso.firebasestorage.app',
    iosBundleId: 'com.example.flutterCoffeeShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGSjOkXCgVbl4uZZWqXKkFTcbZVXHMFEc',
    appId: '1:74866461770:web:e8405fa69a06370b3f6ab3',
    messagingSenderId: '74866461770',
    projectId: 'm-espresso',
    authDomain: 'm-espresso.firebaseapp.com',
    storageBucket: 'm-espresso.firebasestorage.app',
    measurementId: 'G-9QEP0NSM75',
  );
}
